repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [ --fix, --config=pyproject.toml ]
      - id: ruff-format
        args: [ --config=pyproject.toml ]